### ISSUE TITLE
Cannot find Groq AI among the available llms in the settings panel

### ISSUE THREAD

**Issue by AngeloFasciani** [pazoff/GroqAI-Integration#1]
Hi, I installed the Groq AI plugin for the cheshire cat, activated it but cannot find it among the provided llms by the system.
In the log of the container I get:
"ERROR  cat.mad_hatter.plugin.Plugin._load_decorated_functions::292
cheshire_cat_core           | "Error in cat.plugins.groqai_integration.groqai: cannot import name 'PydanticOutputParser' from 'langchain_core.output_parsers' (/usr/local/lib/python3.10/site-packages/langchain_core/output_parsers/__init__.py). Unable to load plugin groqai_integration"".
What could possibly be?

**Comment by pazoff** [comment]
> Hi, I installed the Groq AI plugin for the cheshire cat, activated it but cannot find it among the provided llms by the system.
> 
> In the log of the container I get:
> 
> "ERROR  cat.mad_hatter.plugin.Plugin._load_decorated_functions::292
> 
> cheshire_cat_core           | "Error in cat.plugins.groqai_integration.groqai: cannot import name 'PydanticOutputParser' from 'langchain_core.output_parsers' (/usr/local/lib/python3.10/site-packages/langchain_core/output_parsers/__init__.py). Unable to load plugin groqai_integration"".
> 
> What could possibly be?

Have you restarted the Cheshire cat core container?

**Comment by AngeloFasciani** [comment]
Yes, I did it twice. Does a status page exist to check if the apis are down or something?

**Comment by pazoff** [comment]
> Yes, I did it twice. Does a status page exist to check if the apis are down or something?

They are up, it is working. The plugin is not loading on your cat.

**Comment by pazoff** [comment]
Version of your cat?
on windows/linux/mac?

**Comment by pazoff** [comment]
> Yes, I did it twice. Does a status page exist to check if the apis are down or something?

I've just installed a fresh copy of Cheshire Cat AI - Version 1.5.3, installed the groq plugin and cannot recreate the error - the plugin started and the groq inference is working.
Probably you have old version of the cat?

**Comment by AngeloFasciani** [comment]
Yes, I have, I'm using the 1.4.8 because it's more stable. I've just tried the 1.5.3 and groq works well, but the cat is not that good already: it outputs weird answers, including human prompts that it invented. I believe the 1.5.2 is the best trade-off between stability and groq proper functioning. Also, thank you for the fast replies!
